### ISSUE TITLE
Course Content Checklist

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/Data-Core-Competencies-using-R#10]

**Comment by shazadahmed10** [comment]
Objectives:
-develop R script
-develop exercises to accompany script
-build dataset
-figure our future meeting dates

**Comment by shazadahmed10** [comment]
Updates:
- Dummy dataset will be GoT themed dataset used in Tableau training
- Imran has finished session 1 and session 2 script, Shazad is reviewing and compiling Qs to ask Imran before Imran goes on leave
- Shazad will commence developing accompanying slides next week

**Comment by shazadahmed10** [comment]
Files needed:

- Session 1 Lesson script
- Session 1 exercise script
- Session 1 slides

- Session 2 lesson script
- Session 2 exercise script
- Session 2 slides

**Comment by shazadahmed10** [comment]
To-Dos:
Check in with presenters and facilitators on Wednesday to go over gameplan
Finish course content by Tuesday COB and post to GitHub repo for materials
Slides on workflow/saving files/ R projects
Exercise Scripts for Lessons 1 & 2 (Aliyah working on these based on Lesson script)

**Comment by shazadahmed10** [comment]
@achafetz  just posted the Session 1 script to code tab, will post Session 2 for review later tonight

**Comment by shazadahmed10** [comment]
Posted session 2 script: session 2.zip

**Comment by achafetz** [comment]
we're in meeting all day, so not sure how much time I have to review this. For starters, I would push everything in the the repo (probably the R training one) and then folks can download the whole repo (and reviewers can pull request changes.

![image](https://user-images.githubusercontent.com/8933069/44462416-835e7e00-a5e2-11e8-90c7-db93a386cfdc.png)

**Comment by shapaklyak** [comment]
@shazadahmed10  - agree it would be helpful as @achafetz pointed out. One thing i noticed is that when I open the R training project, nothing opens within it. It's just blank. I have to go to the Rcode folder to open any code.  When I do open the R code for Session 1, line 39 doesn't work because it's pointing to your directory. I don't see a "setting your working directory" section in the code and don't recall there being any in the slide deck. Do you plan to cover this?

**Comment by achafetz** [comment]
My 10am was cancelled so I'll work though this, probably with @jaliasd during that time. In the interim, I've built out a [`feedback branch`](https://github.com/ICPI/Data-Core-Competencies-using-R/tree/feedback) for this repo. 

You can then review the pull request when we finish. I've broken out session 1 into its files.

**Comment by achafetz** [comment]
Also, is the scipt being used as slides? Otherwise, I suggest we delete all the slide references

![image](https://user-images.githubusercontent.com/8933069/44464553-14d0ee80-a5e9-11e8-8c8c-8267ad129a60.png)

**Comment by shazadahmed10** [comment]
@achafetz   Noted...will remove slide references. not all of them will have one in the slide deck anyway

**Comment by abrahamagedewICPI** [comment]
@shazadahmed10, /RawData/**ex1_txtdata**.txt doesnt exist. Did you mean /RawData/**ex1_data**.txt?

**Comment by abrahamagedewICPI** [comment]
@shazadahmed10 , @achafetz @shapaklyak, if it helps I have pushed an rmd file.

**Comment by achafetz** [comment]
Suggested changed for the portion I got through are viewable in the pull request. 

I think an additional piece that would make things more interesting to the participants is posing everything as a questions. For example, rather than just showing here is how we count how many PSNUs are in a country, asking a question will better frame it for them in a way they'll be asked or think about in the future. Instead, you could frame it as a request: The Ambassador needs to know how many districts we have across the 3 countries we work in so we can plan for our COP needs and how targets will be distributed across a country. To approach this, we need to use the `count()` function in R. The way we can approach this is to...

**Comment by shazadahmed10** [comment]
big thanks for reviewing, @achafetz. Made the changes to the scripts

**Comment by shazadahmed10** [comment]
Sessions 1 & 2 files have been posted to the R training repo.
