### ISSUE TITLE
Training Evaluation/Knowledge assessment

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#12]

**Comment by shapaklyak** [comment]
@kkale25  would be good to add the following questions to the post-training evaluation.
were you able to login using the credentials @jb3436 emailed last week to copy over the tableau evaluation? let me know if you need any help w/it. 

- Did you complete the pre-work?
   - options: Yes, No, I wasn't aware of pre-work

- Did you watch any of the videos sent prior to the training?  (Intro video on Using RStudio, ,How to download R & RStudio, Coding Basics)
   - options: Yes, No, I wasn't aware of pre-work

**Comment by kkale25** [comment]
Hi all - please see the link below (and PDF attachment) for the training evaluation form. 

@shazadahmed10 @achafetz - I need you to add the content for Question 10 so we can evaluate people's comfort with certain tasks in R. I'm not the right person to put that in since I don't know much about the content. Remember, these should only be the tasks that you plan to cover/discuss in Sessions 1 and 2.  **Just respond to this issue with the tasks by COB Wednesday (tomorrow) and I'll add them into the form.** 

[https://docs.google.com/forms/d/e/1FAIpQLSdOvB-V4DYdnIMwOjPpC_iXYUOZqekp9umlW-iioq990DhDIg/viewform?usp=sf_link]
[R Training Evaluation_08212018.pdf](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2307695/R.Training.Evaluation_08212018.pdf)

As an example, below are the tasks listed for this question in the Tableau training evaluation:
- Importing datasets into Tableau
- Joining datasets in Tableau
- Creating tableau extracts
- Using custom shape files
- Tableau filters 
- Tableau parameters
- Tableau actions
- Creating maps in Tableau
- Creating dashboards in Tableau
- Creating Tooltips
- Exporting Tableau visuals
- Sharing Tableau visuals

**Comment by shapaklyak** [comment]
@kkale25 did you see the question on content in the pre-training assessment? Use the same fields from that for the content question on the evaluation please. thanks!

**Comment by kkale25** [comment]
Ahh – I didn’t think of that. Ok I’ll add that in.

**Comment by kkale25** [comment]
@shazadahmed10 @shapaklyak 
Looking through the pre-assessment skills questions, it seems that some of those will be covered in later sessions. This post-training eval is just for Sessions 1 and 2 so we'll need to filter the skills questions based on what is actually covered in these first sessions. 

@shazadahmed10 - can you help filter those out and let me know?

**Comment by shapaklyak** [comment]
@kkale25 suggest taking out the last question about attendance at session 3 or 4 since that is pending how tomorrow's training goes. for content keep the following for question  "Please rate yourself on how comfortable you are with the below tasks in RStudio: "
1-3, 6, 7, 8, 9, 10, 11.  is this correct @shazadahmed10 ... not sure about merging.  

![image](https://user-images.githubusercontent.com/5234106/44469876-67fd6e00-a5f6-11e8-9aa7-b23cc8d5b9e8.png)

**Comment by kkale25** [comment]
From @shazadahmed10 

1.	Navigating the RStudio interface 
2.	Understanding how to open/close files in RStudio
3.	Understanding R packages 
4.	Importing a dataset into R
5.	Viewing/exploring the dataset
6.	Sorting variables
7.	Subsetting for variables
8.	Subsetting for values/rows
9.	Creating new variables
10.	Stacking datasets
11.	Using Piping %>% to simplify code
12.	Exporting a dataset
13.	Managing PEPFAR data on your own in RStudio

**Comment by kkale25** [comment]
Final Eval based on @shazadahmed10 and @shapaklyak comments:

https://goo.gl/forms/fmymQHflGxjlzTB22

**Comment by shapaklyak** [comment]
thanks @kkale25 & @shazadahmed10 !
here's a shortened URL to put up on the screen on the slides at the end: https://bit.ly/2MMy5UA

**Comment by kkale25** [comment]
Thanks everyone! I'll close out this issue.
