### ISSUE TITLE
Pre-work

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#14]
Content
	- Familiarize with interface
	- Install packages
	- Load libraries
	- Pull in a dataset (mtcars)
	- View the dataset
	- Sort dataset
	- Ask a couple questions
	
Form
	• Simple handout

**Comment by bshook** [comment]
I have started on this... I have 10 questions and then a user/answer guide. What else do we expect people to do besides sorting? I included a question on exporting to excel but it looks like most of the basic data manipulation or equations have some introduction on data frames to them...

[R Training Pre Work.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2258549/R.Training.Pre.Work.docx)

**Comment by bshook** [comment]
Really showing my knowledge of github by opening and closing this

**Comment by shapaklyak** [comment]
Thanks @bshook , I made a few edits and added in PEPFAR/ICPI logos. 
[R.Training.Pre.Work_kn.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2271351/R.Training.Pre.Work_kn.docx)

**Comment by shazadahmed10** [comment]
I will review this document and tailor the pre-work communication around it

**Comment by shazadahmed10** [comment]
I've reviewed and made some adjustments. The biggest thing I did was eliminate the challenge exercise because the code for exporting will conflict with the code for exporting that will be taught in the session.
If there are no objections, I think this is ready to go out, so all changes need to be accepted and sent.   


[R.Training.Pre.Work_kn_SA.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2275812/R.Training.Pre.Work_kn_SA.docx)

**Comment by achafetz** [comment]
A few comments:

- For the second section, R Studio Interface, rather than having the participants write an X, have each of the quadrants in the image numbered so they can when write down the associated number

![image](https://user-images.githubusercontent.com/8933069/43925229-bb6a5b4a-9bf4-11e8-8e38-54235ee230dc.png)

- For the second section, R Studio Interface, the first question is tough (Put an “X” where you run commands or script) since you can run commands from either II or II in the above image. I would change the language to something like "Note the window where you can load, write, or edit scripts"
- Under questions 4, be careful about case. R is very case sensitive and will not understand any of the listed packages since they start with an upper case in the list and are in fact all lowercase.
- I would recommend changing question 5 to ask about a package in the [tidyverse](https://www.tidyverse.org/packages/)
- Question 6 may be confusing for a first time user - where does this data reside? There is no value in making them work for it since they will never have to load data in this way again. I would write something like "R has a number of datasets  there come preloaded in the software, Let's access the `mtcars` dataset. To do so, we need to write the commands `data(mtcars)` in the console." Then you can have them figure out how to explore it on their own

**Comment by shazadahmed10** [comment]
Also, here is the communication for the pre-work!:

Are you thinking about attending the R training, but have never opened RStudio and are feeling a bit intimidated? 
Have you registered, but are feeling unprepared? 

For those who answered yes, and for those planning the upcoming R training, you are highly encouraged to walkthrough his pre-training exercise to help become familiarized with:

**•	The RStudio interface
•	Interacting with datasets in RStudio 
•	R packages**

This is a self-paced exercise that should take 20-30 minutes to complete. If you have any questions on the pre-work exercise, please come to the R training office hours with your questions!

**Comment by shazadahmed10** [comment]
Updated pre-work document: 

[R.Training.Pre.Work_kn_SA.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2284251/R.Training.Pre.Work_kn_SA.docx)
