### ISSUE TITLE
Pre-training assessment

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Data-Core-Competencies-using-R#8]
Questions from Tableau training: 
[ICPI Tableau Registration & Pre-Training Assessment.pdf](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2203494/ICPI.Tableau.Registration.Pre-Training.Assessment.pdf)

Next step: Katya will revise for R training and share here for comments

FYI: @shazadahmed10 @imujawar @jb3436 @kkale25 @jaliasd @achafetz @HoustonJamie

**Comment by shapaklyak** [comment]
@shazadahmed10 @imujawar @jb3436 @kkale25 @jaliasd @achafetz @HoustonJamie

Please see R Training registration & assessment linked [here](https://goo.gl/forms/bMM4oHLps8ED7dcz1).  This is intended to capture skills across all 4 sessions.
Provide comments in this issue.

to be added - is there an intro video that can be linked in the registration for participants to watch prior to the training ? Ideally this would be something to  familiarize participants w/the layout of R/RStudio and address any basic questions before the training. 

Thanks!

**Comment by shazadahmed10** [comment]
Thanks @shapaklyak! 
I've attached my feedback below and sent you an email.  Let me know if I should make the changes to the pre-assessment! 

[Feedback on Current Assessment.docx](https://github.com/ICPI/Data-Core-Competencies-using-R/files/2229106/Feedback.on.Current.Assessment.docx)

**Comment by shazadahmed10** [comment]
the only thing I could think of that I didn't comment on was office hours.

**Comment by shapaklyak** [comment]
thanks @shazadahmed10 for the comments. i've made updates in the survey. https://goo.gl/forms/ttz4boodSwK3vDYf1 

@achafetz were you planning to review?

**Comment by jb3436** [comment]
I think that for the intro part of the assessment we should remove the links to resources. It makes it look really busy. We can include the links in the email we send out and in the email we send to people confirming their registration. What do you think @shazadahmed10 @shapaklyak @achafetz 

Links to remove from form and include in emails
--
**Please make sure you have the most recent versions of both R AND RStudio installed.** 
Download R: https://cran.cnr.berkeley.edu/ 
Download RStudio: https://www.rstudio.com/products/rstudio/download/ 

**In preparation for this training, we recommend viewing the following videos:**
Good intro video on Using RStudio: https://www.youtube.com/watch?v=riONFzJdXcs
How to download R & RStudio: https://www.youtube.com/watch?v=5ZbjUEg4a1g
Coding Basics: https://www.youtube.com/watch?v=UYclmg1_KLk&t=0s&list=PLqzoL9-eJTNBDdKgJgJzaQcY6OXmsXAHU&index=4

FYI @hessionra

**Comment by achafetz** [comment]
Survey looks solid. The links can be added to the resource page in the wiki.

**Comment by jb3436** [comment]
Drafted registration email to send to ICPI and SI advisors. 
@hessionra  will send OOB 8/2

If anyone has comments - please respond here or via email just sent. @shapaklyak @achafetz @shazadahmed10 @kkale25 

Draft Email
--
To: ICPI analysts and SI advisors and 
CC:  ICPI leads, Irum, and Kelling
Subject: REGISTER: R Training Course – Registration Closes 8/10


Dear ICPI and SI Communities, 
Feel free to share this with your colleagues who may benefit from this course

Please register for the ICPI R Course if you would like to attend sessions. See dates below. The deadline for registration is August 10, 2018. We have a limited number of seats due to the size of the rooms so we will need an accurate headcount for each session. 

**Purpose:**
The purpose of this 4 session course is to learn how to manipulate and visualize the PEPFAR data in R using the MER structured datasets. Additional details and resources will be shared with registered participants. 

**Key Dates:**
- Registration will close on August 10, 2018. 
- Sessions 1&2   Thursday Aug 23, 2018 @ 9:30am - 12:30pm (R basics & Data Manipulation) 
- Session 3:         Thursday Sep 6 , 2018 @ 10:00am - 11:30am (Deeper Data Manipulation)
- Session 4:         Thursday Sep 13, 2018 @ 10:00am - 11:30am (Data Visualization)

**Resources:**
Please make sure you have the most recent versions of both R AND RStudio installed.
- Download R: here
- Download RStudio: here

In preparation for this training, we recommend viewing the following videos:
- Intro video on Using RStudio
- How to download R & RStudio
- Coding Basics

Email with any questions or concerns icpi@state.gov

**Comment by jb3436** [comment]
I added the links to the wiki page

**Comment by jb3436** [comment]
Email sent out 8/2
